"""Deterministic mock provider used by v0.2."""

from typing import List

from .base import AIProvider
from ..schemas import GeneratedCard


class MockAIProvider(AIProvider):
    """Local, deterministic provider with no network or API key dependency."""

    name = "mock"

    def generate_cards(self, chunk) -> List[GeneratedCard]:
        heading = chunk.heading
        snippet = " ".join(chunk.content.split())
        if len(snippet) > 160:
            snippet = snippet[:160].rstrip() + "..."

        return [
            GeneratedCard(
                card_type="basic",
                front=f"什么是「{heading}」？",
                back=snippet or "（该小节暂无正文内容，请手动编辑这张卡片）",
                extra="Generated by mock / mock-v0.2. Please verify manually.",
                tags=["AnkiForge", "mock"],
                source=format_source_display(chunk.source_path, heading),
            )
        ]


def format_source_display(path, heading) -> str:
    """Return a short source label such as `filename.md > Heading`."""
    path_text = str(path or "").strip()
    heading_text = str(heading or "").strip() or "Untitled"

    normalized_path = path_text.replace("\\", "/").rstrip("/")
    filename = normalized_path.rsplit("/", 1)[-1] if normalized_path else ""
    filename = filename or path_text or "Unknown source"
    return f"{filename} > {heading_text}"
