import unittest
from unittest.mock import patch

from ankiforge_ai.ai.providers import create_provider
from ankiforge_ai.ai.providers.base import AIProviderConfig
from ankiforge_ai.ai.providers.mock_provider import MockAIProvider, format_source_display
from ankiforge_ai.ai.providers.openai_compatible import (
    OpenAICompatibleProvider,
    ProviderError,
    _chat_completions_url,
    build_chat_completions_payload,
    extract_assistant_content,
    post_chat_completions,
)
from ankiforge_ai.pipeline.openai_compatible_provider import (
    OpenAICompatibleTransportResponse,
)
from ankiforge_ai.ai.schemas import mock_generate_cards
from ankiforge_ai.importers.md_importer import MarkdownChunk


class ProviderTests(unittest.TestCase):
    def test_mock_provider_generates_one_basic_card_without_network(self):
        provider = MockAIProvider(AIProviderConfig(max_cards_per_chunk=3))
        chunk = MarkdownChunk(
            heading="间隔重复",
            level=1,
            content="间隔重复是一种利用遗忘曲线安排复习的学习方法。",
            source_path="note.md",
        )

        cards = provider.generate_cards(chunk)

        self.assertEqual(len(cards), 1)
        self.assertEqual(cards[0].card_type, "basic")
        self.assertIn("间隔重复", cards[0].front)
        self.assertEqual(cards[0].tags, ["AnkiForge", "mock"])
        self.assertIn("mock", cards[0].tags)
        self.assertEqual(cards[0].source, "note.md > 间隔重复")
        self.assertEqual(
            cards[0].extra,
            "Generated by mock / mock-v0.2. Please verify manually.",
        )

    def test_source_display_uses_filename_not_full_path(self):
        self.assertEqual(
            format_source_display(r"C:\Users\me\vault\note.md", "Heading"),
            "note.md > Heading",
        )
        self.assertEqual(
            format_source_display("/home/me/vault/other.md", "Topic"),
            "other.md > Topic",
        )
        self.assertEqual(
            format_source_display("", ""),
            "Unknown source > Untitled",
        )

    def test_factory_supports_mock_deepseek_and_openai_compatible(self):
        provider = create_provider(AIProviderConfig(ai_provider="mock"))

        self.assertIsInstance(provider, MockAIProvider)
        self.assertIsInstance(
            create_provider(AIProviderConfig(ai_provider="deepseek")),
            OpenAICompatibleProvider,
        )
        self.assertIsInstance(
            create_provider(AIProviderConfig(ai_provider="openai_compatible")),
            OpenAICompatibleProvider,
        )

        with self.assertRaises(ValueError):
            create_provider(AIProviderConfig(ai_provider="openai"))

    def test_legacy_mock_generate_cards_wrapper(self):
        chunk = MarkdownChunk(
            heading="Topic",
            level=1,
            content="Body",
            source_path="source.md",
        )

        cards = mock_generate_cards(chunk)

        self.assertEqual(len(cards), 1)
        self.assertEqual(cards[0].back, "Body")


class OpenAICompatibleProviderTests(unittest.TestCase):
    def test_legacy_http_failure_never_exposes_transport_detail_or_key(self):
        secret = "legacy-provider-secret"
        config = AIProviderConfig(
            ai_provider="deepseek",
            model="deepseek-chat",
            api_base_url="https://api.deepseek.com",
            api_key=secret,
        )
        response = OpenAICompatibleTransportResponse(
            status_code=401,
            json_body=None,
            error_detail=f"Bearer {secret} private material",
        )

        with patch(
            "ankiforge_ai.ai.providers.openai_compatible."
            "OpenAICompatibleHTTPTransport.post_json",
            return_value=response,
        ):
            with self.assertRaises(ProviderError) as context:
                post_chat_completions({}, config)

        rendered = repr(config) + str(context.exception)
        self.assertNotIn(secret, rendered)
        self.assertNotIn("private material", rendered)

    def test_chat_completions_url_appends_endpoint(self):
        self.assertEqual(
            _chat_completions_url("https://api.deepseek.com"),
            "https://api.deepseek.com/chat/completions",
        )
        self.assertEqual(
            _chat_completions_url("https://api.openai.com/v1"),
            "https://api.openai.com/v1/chat/completions",
        )
        self.assertEqual(
            _chat_completions_url("https://example.test/v1/chat/completions"),
            "https://example.test/v1/chat/completions",
        )

    def test_build_payload_requests_json_basic_cards(self):
        chunk = MarkdownChunk(
            heading="Topic",
            level=2,
            content="Important content",
            source_path="note.md",
        )
        config = AIProviderConfig(
            ai_provider="openai_compatible",
            model="test-model",
            api_base_url="https://example.test/v1",
            api_key="test-key",
            max_cards_per_chunk=2,
        )

        payload = build_chat_completions_payload(chunk, config)

        self.assertEqual(payload["model"], "test-model")
        self.assertEqual(payload["response_format"], {"type": "json_object"})
        self.assertIn("Maximum cards: 2", payload["messages"][1]["content"])
        self.assertIn("card_type must be basic", payload["messages"][1]["content"])

    def test_extract_assistant_content(self):
        response = {"choices": [{"message": {"content": '{"cards":[]}'}}]}

        self.assertEqual(extract_assistant_content(response), '{"cards":[]}')

    def test_provider_uses_validated_json_without_network(self):
        chunk = MarkdownChunk(
            heading="Topic",
            level=1,
            content="Body",
            source_path=r"C:\notes\source.md",
        )
        config = AIProviderConfig(
            ai_provider="deepseek",
            model="deepseek-chat",
            api_base_url="https://api.deepseek.com",
            api_key="fake-key",
        )
        api_response = {
            "choices": [
                {
                    "message": {
                        "content": (
                            '{"cards":[{"card_type":"basic","front":"Q",'
                            '"back":"A","extra":"E","tags":["ai"]}]}'
                        )
                    }
                }
            ]
        }

        with patch(
            "ankiforge_ai.ai.providers.openai_compatible.post_chat_completions",
            return_value=api_response,
        ):
            cards = OpenAICompatibleProvider(config).generate_cards(chunk)

        self.assertEqual(len(cards), 1)
        self.assertEqual(cards[0].front, "Q")
        self.assertEqual(cards[0].source, "source.md > Topic")
        self.assertIn(
            "Generated by deepseek / deepseek-chat. Please verify manually.",
            cards[0].extra,
        )


if __name__ == "__main__":
    unittest.main()
