import unittest

from ankiforge_ai.ai.validators import (
    CardValidationError,
    cards_from_json_text,
    normalize_tag,
    validate_cards_payload,
)
from ankiforge_ai.importers.md_importer import MarkdownChunk


class ValidatorTests(unittest.TestCase):
    def test_validates_basic_cards_and_adds_local_source(self):
        chunk = MarkdownChunk(
            heading="过拟合",
            level=2,
            content="过拟合是模型记住训练集噪声。",
            source_path=r"C:\notes\ml.md",
        )
        payload = {
            "cards": [
                {
                    "card_type": "basic",
                    "front": "什么是过拟合？",
                    "back": "模型记住训练集噪声。",
                    "extra": "需要验证集检测。",
                    "tags": ["ml", "ai", "ml"],
                    "source": "model must not control this",
                }
            ]
        }

        cards = validate_cards_payload(payload, chunk, max_cards_per_chunk=3)

        self.assertEqual(len(cards), 1)
        self.assertEqual(cards[0].source, "ml.md > 过拟合")
        self.assertEqual(cards[0].tags, ["ml", "ai"])
        self.assertTrue(cards[0].extra.startswith("需要验证集检测。"))
        self.assertIn("Generated by unknown / unknown", cards[0].extra)

    def test_extra_empty_gets_provider_model_metadata(self):
        chunk = MarkdownChunk("Heading", 1, "Body", "note.md")
        payload = {
            "cards": [
                {
                    "card_type": "basic",
                    "front": "Q",
                    "back": "A",
                    "extra": "",
                    "tags": [],
                }
            ]
        }

        cards = validate_cards_payload(
            payload,
            chunk,
            max_cards_per_chunk=3,
            provider_name="deepseek",
            model="deepseek-chat",
        )

        self.assertEqual(
            cards[0].extra,
            "Generated by deepseek / deepseek-chat. Please verify manually.",
        )

    def test_extra_non_empty_is_preserved_with_metadata_appended(self):
        chunk = MarkdownChunk("Heading", 1, "Body", "note.md")
        payload = {
            "cards": [
                {
                    "card_type": "basic",
                    "front": "Q",
                    "back": "A",
                    "extra": "易混点：不要和 B 混淆。",
                    "tags": [],
                }
            ]
        }

        cards = validate_cards_payload(
            payload,
            chunk,
            max_cards_per_chunk=3,
            provider_name="openai_compatible",
            model="model-x",
        )

        self.assertEqual(
            cards[0].extra,
            (
                "易混点：不要和 B 混淆。\n\n"
                "Generated by openai_compatible / model-x. Please verify manually."
            ),
        )

    def test_normalize_tags(self):
        chunk = MarkdownChunk("Heading", 1, "Body", "note.md")
        payload = {
            "cards": [
                {
                    "card_type": "basic",
                    "front": "Q",
                    "back": "A",
                    "tags": [
                        " Machine Learning ",
                        "",
                        "机器学习",
                        "Machine   Learning",
                        "This tag is far too long to be useful in Anki",
                    ],
                }
            ]
        }

        cards = validate_cards_payload(payload, chunk, max_cards_per_chunk=3)

        self.assertEqual(cards[0].tags, ["machine_learning", "机器学习"])
        self.assertEqual(normalize_tag("Spaced Repetition"), "spaced_repetition")

    def test_rejects_non_basic_cards_in_v02(self):
        chunk = MarkdownChunk("Heading", 1, "Body", "note.md")

        with self.assertRaises(CardValidationError):
            validate_cards_payload(
                {"cards": [{"card_type": "cloze", "front": "Q", "back": "A"}]},
                chunk,
                max_cards_per_chunk=3,
            )

    def test_rejects_empty_front_or_back(self):
        chunk = MarkdownChunk("Heading", 1, "Body", "note.md")

        with self.assertRaises(CardValidationError):
            validate_cards_payload(
                {"cards": [{"card_type": "basic", "front": "", "back": "A"}]},
                chunk,
                max_cards_per_chunk=3,
            )

    def test_rejects_invalid_json(self):
        chunk = MarkdownChunk("Heading", 1, "Body", "note.md")

        with self.assertRaises(CardValidationError):
            cards_from_json_text("not json", chunk, max_cards_per_chunk=3)

    def test_limits_cards_to_max_cards_per_chunk(self):
        chunk = MarkdownChunk("Heading", 1, "Body", "note.md")
        payload = {
            "cards": [
                {"card_type": "basic", "front": "Q1", "back": "A1"},
                {"card_type": "basic", "front": "Q2", "back": "A2"},
            ]
        }

        cards = validate_cards_payload(payload, chunk, max_cards_per_chunk=1)

        self.assertEqual(len(cards), 1)
        self.assertEqual(cards[0].front, "Q1")


if __name__ == "__main__":
    unittest.main()
